
#浏览器driver配置，用来控制启动的浏览器和是否有误界面
[DRIVER]

#要启动的浏览器：chrome，ie，firefox
#gui表示是否有无界面

browser = chrome
gui = no
url = xxxxxx


[EMAIL]
sender = marsmeng66@163.com
password = JCmdSbNqr24yiuh7
receiver = ['784007352@qq.com','15163722299@163.com']

[email]
sender = marsmeng66@163.com
password = JCmdSbNqr24yiuh7
receiver = ['784007352@qq.com','15163722299@163.com']
smtpserver = smtp.163.com


[dingtalk]
roboturl = https://oapi.dingtalk.com/robot/send?access_token=d1cbcf29f57908eb5302a4dab5ada6cfa8baafaaebc36aadc3c588ffc7ece50c



[DATABASE]


[USER]
username = xxxx
password = xxxxx





