
#浏览器driver配置，用来控制启动的浏览器和是否有误界面
[DRIVER]

#要启动的浏览器：chrome，ie，firefox
#gui表示是否有无界面

browser = chrome
gui = no
url = xxxxxx


[EMAIL]
host = 127.0.0.1



[DATABASE]


[USER]
username = xxxx
password = xxxxx





